# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts-as-tree-with-dotted-ids}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Heinemeier Hansson", "Xavier Defrang"]
  s.date = %q{2010-11-09}
  s.description = %q{}
  s.email = %q{tma@freshbit.ch}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/active_record/acts/tree_with_dotted_ids.rb",
     "lib/acts-as-tree-with-dotted-ids.rb"
  ]
  s.homepage = %q{http://github.com/tma/acts-as-tree-with-dotted-ids}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A drop in replacement for acts_as_tree with super fast ancestors and subtree access}
  s.test_files = [
    "test/acts_as_tree_test.rb",
     "test/schema.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
  end
end

